### ISSUE TITLE
Typography section should note the secondary font type must be imported

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/patterns#1]
I wasn't familiar with Montserrat, but I'm also not very familiar with standard fonts so for all I know it could be a system font. Looking through [the code](https://github.com/CityOfPhiladelphia/patterns/blob/gh-pages/_scss/patterns/base/_typography.scss#L2) I saw that you're actually importing it, so I used that. Just a thought!

**Comment by kdemi** [comment]
If you are pointing at the complied CSS file in /dist/VERSION/css/patterns.css then the font should be imported for you. But I agree, it should be noted for both Monserrat and Open Sans.

**Comment by kdemi** [comment]
See http://cityofphiladelphia.github.io/patterns/#p-fonts

**Comment by gsf** [comment]
:+1: to not relying on system fonts.
