### ISSUE TITLE
"alternate divide" headers in IE11

### ISSUE THREAD

**Issue by rbrtmrtn** [CityOfPhiladelphia/patterns#107]
The `<h2 class="alternate divide">` elements in Property Search appear with a blue line in Chrome:

![image](https://cloud.githubusercontent.com/assets/1463553/19395586/55d3b3b0-920c-11e6-8f51-609d20f80ca3.png)

but are missing the line in IE11:

![image](https://cloud.githubusercontent.com/assets/1463553/19395533/16abe64e-920c-11e6-990d-a2ffd945ad29.png)

It looks like all the attributes for `alternate divide` are being overridden by "inline style":

![image](https://cloud.githubusercontent.com/assets/1463553/19396785/bd21fd96-9212-11e6-90ed-cbb805e0527d.png)

**Comment by karissademi** [comment]
Thanks for the note @rbrtmrtn! There's only partial support for `display:flex` in IE11, unfortunately. The good news is, that pattern will likely be deprecated in the near future.

**Comment by rbrtmrtn** [comment]
Got it, thanks for following up @karissademi! I'll go ahead and close this out.
