### ISSUE TITLE
Thick footer

### ISSUE THREAD

**Issue by gsf** [CityOfPhiladelphia/patterns#12]
We've discussed the potential for a thick footer a few times, with possibilities including the repetition of topics, etc. in the platform at alpha.phila.gov. I just ran into this with the new property search where I barely managed to squeeze the following into one line:
- link back to the main site,
- the feedback link,
- the terms of use link,
- and language links.

When I tried to create another row it got cut off by the height set on the footer. IIRC a footer without height makes the min-height on page tricky, so maybe the answer is I should just override the height in my local stylesheet. Thoughts?

A separate but related issues is that on mobile, with the items in the footer stacking, there isn't enough room between them for a finger tap. So in any case we should give that row more height.

**Comment by kdemi** [comment]
The 0.3.0 release includes "fat footer" support. You can either just use the single row "classic" footer or include markup for more links in the "fat" section.

Either way, you will need to include the patterns.min.js file to allow the footer to have a variable height and remain sticky.
