### ISSUE TITLE
Suggestion: Add instructions page

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/patterns#13]
Based on my experience adding patterns to budget app: I've worked in bootstrap before but hadn't worked in foundation. What would have been helpful for me was an instructions page that told me things like:

* It's based off foundation, not bootstrap. You probably shouldn't use it with bootstrap.
* You don't need to include foundation's CSS
* You should include our versioned CSS file (I actually tried to explain this to a couple of folks on our team in a workshop and there was no easy way to even get the embeddable, gh-pages URL except to view-source on the patterns site itself)
* You should put your content inside of a container, or whatever foundation wants you to do (not really sure how to word this one, but it was confusing coming from bootstrap. maybe it's not necessary)

Perhaps even a totally separate `sample.html` with just the CSS include, a container `<div>`, and a sample element like a textbox inside? I anticipate people would likely copy & paste all of it as a starting boilerplate on which to build, like our own html5boilerplate.

**Comment by gsf** [comment]
Good points. I've felt similar in building the new property app.

Seems to me the README is the place for this documentation. If it isn't clear we should fix it up. I did add the full link to the versioned CSS there already.

Along the lines of the sample.html file, I've been using the full pages linked to in the pattern site header for reference. One thing that could help is if those pages are naked, i.e. they include none of the pattern header, etc.

**Comment by timwis** [comment]
Oh wow, I didn't even realize there was a README somehow. Perhaps there's just a way to include the README on the actual page? We advertise the gh-pages URL when we say "look at our pattern portfolio" rather than the github repo. How do we direct viewers to the readme when the want to "get started"?

**Comment by gsf** [comment]
Could just link to GitHub as suggested in #9.

**Comment by kdemi** [comment]
There is now a link back to the repo from the main patterns page.  However, having a boilerplate would be very useful for getting started quickly.
