### ISSUE TITLE
Modal

### ISSUE THREAD

**Issue by gsf** [CityOfPhiladelphia/patterns#15]
Be nice to have a pattern for modals so I don't have to think about it. :grinning:

**Comment by gsf** [comment]
Pretty much just the basic foundation reveal would be fine for me.
http://foundation.zurb.com/docs/components/reveal.html

**Comment by kdemi** [comment]
That's what the other sites have used. :)

**Comment by gsf** [comment]
Great! Let's document it. :grinning:
