### ISSUE TITLE
Include unminified files in releases

### ISSUE THREAD

**Issue by gsf** [CityOfPhiladelphia/patterns#18]
A thought for the next release: if we include unminified versions of the css and js in the release folders then it'll be easier to switch to those and debug when needed.

**Comment by kdemi** [comment]
This is done for the js. The css gets complied from sass, so I'm not sure having an non-minified version would really help. I think could include a version with source mapping, but I'm not 100% sure that would work.

**Comment by gsf** [comment]
Just unminifed JS is great. Thanks!
