### ISSUE TITLE
Add a pattern for the <title> tag?

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/patterns#2]
Should I use `City of Philadelphia - Page Title`, `City of Phila : Page Title`, or `Page Title - Phila.gov`?

**Comment by kdemi** [comment]
None of the above! On alpha the pattern is `Page Title | phila.gov`.

**Comment by gsf** [comment]
I agree it's a pattern worth including in the portfolio.

**Comment by kdemi** [comment]
Added: http://cityofphiladelphia.github.io/patterns/#p-title-tag
