### ISSUE TITLE
Add a pattern for the site/application title?

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/patterns#3]
In phila.gov 3.0, we included the department name as part of the logo ([example](http://www.phila.gov/parksandrecreation)). Not that we'd want to do that here, but where *do* we put the site name or application name? Particularly if it doesn't fall under clearly defined breadcrumbs, and it's its own distinct site or application that wants to have a look and feel consistent with our patterns?

**Comment by kdemi** [comment]
This has been added: http://cityofphiladelphia.github.io/patterns/#p-header-app

**Comment by timwis** [comment]
Looks great! May want to consider making a determination on the header being a link. On the [budget](http://www.phila.gov/budget) app it's not a link, but on the [contract data](http://www.phila.gov/contracts/data) site it is

**Comment by gsf** [comment]
Yeah I just turned it into a link on the property site -- it generally should be. I imagine we'll want to style the `<a>` with color: #353535 as well.

**Comment by kdemi** [comment]
The hover color of the header text should be blue, but the link should be
black.

I'll make sure these get added.

**Comment by gsf** [comment]
Hover color in the header? Interesting.
