### ISSUE TITLE
Adding icon class to button makes it full width

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/patterns#40]
Adding the `icon` class to a button per the pattern portfolio changes the button to full-width / expanded. I'd like to be able to add an icon to a button without making it full-width.

`<a href="#" class="button icon">Button with Icon<i class="fa fa-bell"></i></a>`

**Comment by kdemi** [comment]
This has been fixed in https://github.com/CityOfPhiladelphia/patterns/commit/86f6be899db443366c216d9c519462df8c770bcc
