### ISSUE TITLE
Suggestion: Copy to clipboard button on code blocks

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/patterns#52]
For quick & easy copy & pasting of code blocks: [clipboard.js](https://zenorocha.github.io/clipboard.js/) (saw it recently on hacker news). Makes it easier than having to highlight, hope you didn't miss anything (like a closing HTML bracket), and copy. Just a suggestion!

**Comment by karissademi** [comment]
I thought about this a little while ago, but didn't have time to implement it. I agree it would be a useful feature.

**Comment by karissademi** [comment]
Closed in #53
