### ISSUE TITLE
Application title on mobile takes up two lines

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/patterns#55]
For [open budget](http://www.phila.gov/openbudget/) we had a liberty-bell-only logo and title on the same line. It looks like styles have been added to put this on its own line? Or was the pattern just never incorporated?

**Comment by karissademi** [comment]
We felt the bell alone wasn't strong enough as a brand to ensure users
would know they were on a phila.gov site without that text displayed.

Happy to revisit this to find another solution.

**Comment by karissademi** [comment]
After discussion with @mjumbewu, we decided a smaller logo is a requirement for applications. The application header now contains a version of the phila.gov logo without the "City of Philadelphia" text. Added in https://github.com/CityOfPhiladelphia/patterns/commit/cdd6b86f776ff521806dbfb3ad1a85f57a903b53#diff-a1a7e2e12aaf607419e8a94f2a368e24R12
