### ISSUE TITLE
Navigation pattern hides other buttons on small screens

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/patterns#58]
The navigation pattern (last one on the page) appears to hide the other nav buttons on small screens

<img width="331" alt="screen shot 2015-10-21 at 18 09 13" src="https://cloud.githubusercontent.com/assets/761444/10651661/ea01b414-781e-11e5-8094-b5dbcccfb189.png">

**Comment by karissademi** [comment]
Fixed in a5e8ef65e4faa23d2fffc322d756164cc09f7359.
