### ISSUE TITLE
Redundant JS include

### ISSUE THREAD

**Issue by timwis** [CityOfPhiladelphia/patterns#7]
According to [Foundation docs](http://foundation.zurb.com/docs/javascript.html), `foundation.min.js` includes all JavaScript plugins, so [footer.html#L9](https://github.com/CityOfPhiladelphia/patterns/blob/gh-pages/_includes/footer.html#L9) should be unnecessary. Haven't tested though, just a heads up.

**Comment by gsf** [comment]
Side note: how necessary is the foundation JS? Should it be included in all of our apps? If so that should be added to the README.

**Comment by kdemi** [comment]
At the moment Foundation JS is not necessary for anything in the Portfolio. I included it so I could use the Foundation menu. Will test and remove the unnecessary call.
