### ISSUE TITLE
Missing steps/dependencies in setup instructions

### ISSUE THREAD

**Issue by antislice** [CityOfPhiladelphia/patterns#95]
Helped someone set this up the other day, and it's missing a couple things that would make it much smoother.

Existing:
1. Install Jekyll `$ gem install jekyll`
1. Clone this repository
1. `cd` into the patterns directory
1. `$ jekyll serve` <- We were missing the `pygments.rb` gem
1. Navigate to http://localhost:4000/patterns
1. Run `$ grunt watch` <- `grunt` wasn't installed or in the dev dependencies in `package.json`

Suggestions:
- Include a Gemfile with `jekyll` and `pygments.rb` (or include a step to `gem install pygments.rb`)
- Include `grunt` in package.json
- Add a step to run `bundle install` and `npm install`

**Comment by michaelck** [comment]
Thanks for the feedback & suggestions, @antislice. We'll take care of this shortly.
