### ISSUE TITLE
Bare minimum also requires jQuery, Foundation

### ISSUE THREAD

**Issue by rbrtmrtn** [CityOfPhiladelphia/patterns#98]
For the Bare Minimum section in [README.md](https://github.com/CityOfPhiladelphia/patterns/blob/gh-pages/README.md) -- if I drop that into the `head` of an empty HTML file I get:

    tablesaw.stackonly.js:30 Uncaught ReferenceError: jQuery is not defined

And after pulling in jQuery:

    jquery-3.1.0.min.js:2 Uncaught TypeError: a(...).foundation is not a function

Should there be a note on the external req's?

**Comment by michaelck** [comment]
Thanks, @rbrtmrtn. These docs need more attention for sure. Will have an update shortly.

**Comment by rbrtmrtn** [comment]
@michaelck new readme looks great! :+1:
