### ISSUE TITLE
bower.json missing some dependencies

### ISSUE THREAD

**Issue by rbrtmrtn** [CityOfPhiladelphia/patterns#99]
I think some of the `bower_components` might be missing from `bower.json`. Not sure if they're still used or not 😄

**Comment by karissademi** [comment]
Thanks for pointing this out @rbrtmrtn. Expect an update soon.

**Comment by michaelck** [comment]
closed by #102

**Comment by michaelck** [comment]
@rbrtmrtn Not sure if you had a chance to look through the PR that closes this issue, but Bower has been removed. You'll likely need to run `npm install` after pulling the latest `gh-pages`.

**Comment by rbrtmrtn** [comment]
@michaelck thanks for the update. Just wondering, was there a particular reason Bower support was removed? I have this idea in my head of being able to `bower install https://github.com/CityOfPhiladelphia/patterns.git`, but maybe there's a better way to quickly bootstrap a new app like that?

**Comment by michaelck** [comment]
@rbrtmrtn you'll want to talk to @karissademi about the details on this one

**Comment by karissademi** [comment]
@rbrtmrtn You'll be able to do an `npm install` to pull in all the dependencies and get started just as quickly. I set up patterns with Bower a long time ago and began vendoring, but at some point that got out of sync with the actual dependencies. 

There's been a lot written about npm vs Bower, and when you should pick one over the other. While Bower is "made for the front-end" npm does all the things we need it to do. To me it's a "half dozen of one, 6 of the other" situation. Certainly we didn't both.

**Comment by rbrtmrtn** [comment]
Great explanation @karissademi , thank you! `npm install` works for me 😄

**Comment by karissademi** [comment]
Thank _you_ for leaving feedback @rbrtmrtn! Glad it's working for you.
